//! Opaque identifier for a dispense-amount reservation held in the wallet.

use uuid::Uuid;

/// Opaque identifier for a wallet-held reservation against future dispense.
///
/// Generated by the wallet at `Wallet::reserve_for_dispense` and consumed by
/// `Wallet::release_dispense_reservation` and `Wallet::finalize_dispense_reservation`.
/// Backed by a UUID v4 to make the identifier safe to log and to keep collisions
/// statistically impossible across restarts and across multiple wallet processes
/// reading the same storage volume.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ReservationId(Uuid);

impl ReservationId {
    /// Generates a fresh reservation identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Wraps a raw [`Uuid`] as a `ReservationId`.
    ///
    /// Callers outside Zally should obtain a `ReservationId` from wallet operations
    /// rather than constructing it from a raw UUID; this constructor exists for
    /// storage-impl translation and for test fixtures.
    #[must_use]
    pub const fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }

    /// Exposes the underlying [`Uuid`].
    #[must_use]
    pub const fn as_uuid(self) -> Uuid {
        self.0
    }
}

impl Default for ReservationId {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reservation_id_round_trips_uuid() {
        let uuid = Uuid::new_v4();
        let id = ReservationId::from_uuid(uuid);
        assert_eq!(id.as_uuid(), uuid);
    }

    #[test]
    fn reservation_id_new_is_unique_within_a_batch() {
        let a = ReservationId::new();
        let b = ReservationId::new();
        assert_ne!(a.as_uuid(), b.as_uuid());
    }
}
